num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0,1
client_optimizer: sgd
dataset: imagenet100
dataset_path: ./data
frequency_save: 0
batch_size: 128
lr: 0.005
lr_scheduler: ReduceLROnPlateau
model: pretrained-resnet50
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 20
